# site settings
title: Lgreco | ΛGreco
google_analytics_id: UA-47897501-1
# url: "http://lgreco.eu"
shareaholic_app_id: 23126307
shareaholic_site_id: bcf4fb9a3f70ecd99f1e09171fcf2fa1
# Get this from the url https://cse.google.com/cse/setup/basic?cx=006765593147615178379:lnmf5jvfzky
# or the v1 codebase
google_search: 006765593147615178379:lnmf5jvfzky
send_contact_to: lgreco.eu@gmail.com

t: 
 el:
  company: "Λgreco"
  moto: "Πάθος για ποιότητα"
  search: "Αναζήτηση"
 en:
  company: "Lgreco"
  moto: "Passion for quality"
  search: "Search"

# standard jekyll configuration
exclude:
- Gemfile
- Gemfile.lock
- README.md
- "*.bat"
- CNAME
- "*.sln"
- "*.suo"